version: "3"

services:
  notify:
    build: "."
    command: "notify-service"
    links:
      - "nats"
      - "postgres"
    ports:
      - "8080"
    env_file: .env

  query:
    build: "."
    command: "query-service"
    links:
      - "postgres"
      - "nats"
      - "elasticsearch"
    ports:
      - "8080"
    env_file: .env

  pusher:
    build: "."
    command: "pusher-service"
    links:
      - "nats"
    ports:
      - "8080"
    env_file: .env

  postgres:
    build: "./.docker/postgres"
    restart: "always"
    env_file: .env

  nats:
    image: "nats-streaming:0.9.2"
    restart: "always"

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.3.0'
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
      - 'bootstrap.memory_lock=false'
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"

  nginx:
    build: "./.docker/nginx"
    ports:
      - "8080:80"
    links:
      - "notify"
      - "query"
      - "pusher"
